### ISSUE TITLE
Incompatibility with media queries

### ISSUE THREAD

**Issue by MarcioOliveira** [eduardoboucas/postcss-cssential#1]
I have noticed that media queries marked with !cssential do not get appended to the html.

**Comment by susannakosic** [comment]
Plus 1

**Comment by eduardoboucas** [comment]
Thanks. I will look into this over the weekend.

**Comment by eduardoboucas** [comment]
I have pushed [a new branch](https://github.com/eduardoboucas/postcss-cssential/tree/v_110) where this is fixed (as well as #2). Can you please pull that branch to see if that solves your issues, so that I can publish the new version?

The new version allows you to define entire media queries as essential:

```css
@media only screen (min-width: 400px) {
	/*!cssential*/
	body {
		color: blue;
	}

	a {
		text-decoration: underline;
	}
}
```

Or individual declarations inside a media query:

```css
@media only screen (min-width: 400px) {
	body {
		/*!cssential*/
		color: blue;
	}

	a {
		/*!cssential*/
		text-decoration: underline;
	}
}
```
